### ISSUE TITLE
Not working in angular 18.

### ISSUE THREAD

**Issue by bhaveshpatel200** [AngelCareaga/ngx-custom-modal#1]
Hi,

When i am trying to install this package in Angular 18 which gives peer dependency error:

```typescript
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^17.3.11" from ngx-custom-modal@18.0.1
``` 

Could you please update and support for Angular 18?

**Comment by AngelCareaga** [comment]
Thanks for the note, I have updated it. Please verify that it works correctly for your case.


https://github.com/AngelCareaga/ngx-custom-modal/releases/tag/18.0.2

**Comment by bhaveshpatel200** [comment]
Thanks for quick update. its working fine now.
